import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "surface-dim": "#d8dae1",
        "on-tertiary-fixed-variant": "#43474a",
        "inverse-surface": "#2e3036",
        "surface-container-high": "#e7e8ef",
        "surface-container-highest": "#e1e2e9",
        "on-background": "#191c21",
        "on-secondary-fixed": "#191c1d",
        "outline": "#727783",
        "inverse-on-surface": "#eff0f8",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#454748",
        "background": "#f9f9ff",
        "surface": "#f9f9ff",
        "on-tertiary-container": "#d1d4d7",
        "secondary-fixed-dim": "#c5c7c8",
        "on-tertiary-fixed": "#181c1e",
        "error": "#ba1a1a",
        "surface-bright": "#f9f9ff",
        "primary-fixed": "#d5e3ff",
        "on-tertiary": "#ffffff",
        "secondary": "#5c5f60",
        "on-primary": "#ffffff",
        "tertiary-container": "#585c5f",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e0e3e6",
        "on-surface-variant": "#424751",
        "inverse-primary": "#a7c8ff",
        "surface-tint": "#0b5eaf",
        "primary": "#004482",
        "primary-fixed-dim": "#a7c8ff",
        "tertiary": "#404547",
        "on-secondary-container": "#626566",
        "on-error-container": "#93000a",
        "on-primary-container": "#bdd5ff",
        "on-surface": "#191c21",
        "surface-variant": "#e1e2e9",
        "outline-variant": "#c2c6d3",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-primary-fixed": "#001b3b",
        "secondary-fixed": "#e1e3e4",
        "on-primary-fixed-variant": "#004788",
        "primary-container": "#005bac",
        "surface-container": "#ecedf5",
        "secondary-container": "#e1e3e4",
        "surface-container-low": "#f2f3fb",
      },
      spacing: {
        "xs": "4px",
        "grid-gutter": "12px",
        "unit": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "container-padding": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "data-heavy": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "h1": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-heavy": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
